# Generated by Django 5.0.3 on 2024-03-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maintenace_Tasks',
            new_name='Maintenance_Tasks',
        ),
    ]
